build.sbt
modules/avro-codec/src/main/scala/io/renku/avro/codec/json/AvroJsonDecoder.scala
modules/avro-codec/src/main/scala/io/renku/avro/codec/json/AvroJsonEncoder.scala
modules/avro-codec/src/test/scala/io/renku/avro/codec/AvroReaderSpec.scala
modules/avro-codec/src/test/scala/io/renku/avro/codec/json/JsonCodecSpec.scala
modules/http4s-avro/README.md
modules/http4s-avro/src/main/scala/io/renku/search/http/avro/AvroEntityCodec.scala
modules/messages/src/main/avro/api.avdl
modules/messages/src/main/avro/messages.avdl
modules/redis-client/src/test/scala/io/renku/redis/client/util/TestSearchRedisServer.scala
modules/search-api/README.md
modules/search-api/src/main/scala/io/renku/search/api/HttpApplication.scala
modules/search-api/src/main/scala/io/renku/search/api/HttpServer.scala
modules/search-api/src/main/scala/io/renku/search/api/Microservice.scala
modules/search-api/src/main/scala/io/renku/search/api/SearchApi.scala
modules/search-api/src/main/scala/io/renku/search/api/SearchApiImpl.scala
modules/search-api/src/test/scala/io/renku/search/api/SearchApiSpec.scala
modules/search-provision/src/main/scala/io/renku/search/provision/Microservice.scala
modules/search-provision/src/main/scala/io/renku/search/provision/SearchProvisioner.scala
modules/search-provision/src/test/scala/io/renku/search/provision/SearchProvisionerSpec.scala
modules/search-solr-client/src/main/scala/io/renku/search/solr/client/SearchSolrClient.scala
modules/search-solr-client/src/main/scala/io/renku/search/solr/client/SearchSolrClientImpl.scala
modules/search-solr-client/src/test/scala/io/renku/search/solr/client/SearchSolrClientGenerators.scala
modules/search-solr-client/src/test/scala/io/renku/search/solr/client/SearchSolrClientSpec.scala
modules/search-solr-client/src/test/scala/io/renku/search/solr/client/TestSearchSolrServer.scala
project/Dependencies.scala

This PR brings some initial implementation of the Search API service.

feat: a simple service exposing Search API

---

modules/redis-client/src/main/scala/io/renku/queue/client/Message.scala
modules/redis-client/src/main/scala/io/renku/queue/client/QueueClient.scala
modules/redis-client/src/main/scala/io/renku/redis/client/RedisQueueClient.scala
modules/redis-client/src/test/scala/io/renku/redis/client/RedisClientGenerators.scala
modules/redis-client/src/test/scala/io/renku/redis/client/RedisQueueClientSpec.scala
modules/search-api/src/test/scala/io/renku/search/api/SearchApiSpec.scala
modules/search-provision/src/main/scala/io/renku/search/provision/SearchProvisioner.scala
modules/search-provision/src/test/scala/io/renku/search/provision/SearchProvisionerSpec.scala
modules/search-solr-client/src/main/scala/io/renku/search/solr/client/SearchSolrClient.scala
modules/search-solr-client/src/main/scala/io/renku/search/solr/client/SearchSolrClientImpl.scala
modules/search-solr-client/src/test/scala/io/renku/search/solr/client/SearchSolrClientSpec.scala

This change makes the Provisioning flow try some simplistic approach to determine if the message's payload is binary or JSON encoded and use the appropriate decoding strategy.

feat: provisioning flow to figure out message payload encoding

---

build.sbt
modules/http4s-borer/src/main/scala/io/renku/search/http/borer/TapirBorerJson.scala
modules/redis-client/src/main/scala/io/renku/redis/client/RedisQueueClient.scala
modules/search-api/src/main/scala/io/renku/search/api/HttpApplication.scala
modules/search-api/src/main/scala/io/renku/search/api/Project.scala
modules/search-api/src/main/scala/io/renku/search/api/SearchApiImpl.scala
modules/search-api/src/test/scala/io/renku/search/api/SearchApiSpec.scala
project/Dependencies.scala

This PR:
* introduces Tapir to the `search-api` service
* exposes a new `GET /docs` API with a swagger page listing service's APIs

feat: tapir on search-api

---

build.sbt
modules/search-api/src/main/scala/io/renku/search/api/HttpApplication.scala
project/Dependencies.scala

This PR:
* removes the existing Swagger page from the Search API endpoints
* adds a new `/search/spec.json` API

feat: OpenAPI docs exposed as /search/spec.json

---

modules/commons/src/main/scala/io/renku/logging/LoggingSetup.scala
modules/commons/src/test/scala/io/renku/search/GeneratorSyntax.scala
modules/commons/src/test/scala/io/renku/search/LoggingConfigure.scala
modules/redis-client/src/test/scala/io/renku/redis/client/RedisClientGenerators.scala
modules/redis-client/src/test/scala/io/renku/redis/client/RedisQueueClientSpec.scala
modules/renku-redis-client/src/test/scala/io/renku/queue/client/QueueClientSpec.scala
modules/search-api/src/test/scala/io/renku/search/api/SearchApiSpec.scala
modules/search-provision/src/test/scala/io/renku/search/provision/project/ProjectCreatedProvisionerSpec.scala
modules/search-provision/src/test/scala/io/renku/search/provision/user/UserAddedProvisionerSpec.scala
modules/search-query/src/main/scala/io/renku/search/query/SortableField.scala
modules/search-query/src/test/scala/io/renku/search/query/QueryGenerators.scala
modules/search-solr-client/src/main/scala/io/renku/search/solr/query/LuceneQueryEncoders.scala
modules/search-solr-client/src/main/scala/io/renku/search/solr/query/SolrTokenEncoder.scala
modules/search-solr-client/src/test/scala/io/renku/search/solr/client/SearchSolrClientGenerators.scala
modules/search-solr-client/src/test/scala/io/renku/search/solr/client/SearchSolrClientSpec.scala
modules/search-solr-client/src/test/scala/io/renku/search/solr/query/LuceneQueryInterpreterSpec.scala
modules/solr-client/src/main/scala/io/renku/solr/client/QueryData.scala
modules/solr-client/src/test/scala/io/renku/solr/client/SolrClientGenerator.scala
modules/solr-client/src/test/scala/io/renku/solr/client/SolrClientSpec.scala

- fixes the solr query generated when the user only specifies sort terms
- moves `def generateOne` extension methods to commons module
- adds a `LoggingConfigure` trait for tests to avoid logging too much stuff. If mixed in, the verbosity is set to `0` meaning only ERROR messages will be printed. It is not applied to all specs

fix: Create correct solr query in case only `sort` terms are specfified

---

flake.nix
modules/config-values/src/main/scala/io/renku/search/config/ConfigValues.scala
modules/search-query/src/test/scala/io/renku/search/query/QueryGenerators.scala
modules/solr-client/src/main/scala/io/renku/solr/client/SolrClientImpl.scala
modules/solr-client/src/main/scala/io/renku/solr/client/SolrConfig.scala
modules/solr-client/src/test/scala/io/renku/solr/client/util/SolrServerSuite.scala

To avoid dirty reads we need for now update with hard commits. In the future we can run certain updates in parallel.

Remove commitWithin global config option

---

modules/search-provision/src/main/scala/io/renku/search/provision/events/Projects.scala
modules/search-provision/src/main/scala/io/renku/search/provision/events/syntax.scala
modules/search-provision/src/main/scala/io/renku/search/provision/handler/DocumentMerger.scala
modules/search-provision/src/test/scala/io/renku/search/provision/project/ProjectUpdatedProvisioningSpec.scala

This pr allows to first receive a project-update message and later a corresponding project-created message. The initial update message will be stored as a partial entity document (same as done already with project-auth-added)

feat: Create partial documents from ProjectUpdated messages

---

modules/events/src/main/scala/io/renku/search/events/MessageHeader.scala
modules/solr-client/src/test/scala/io/renku/solr/client/SolrClientSpec.scala

- Try first json when decoding the message header, as this is sent from data services this way
- The payload must be decoded according to the `contentType` value in the message header

Reduce content-type logging when decoding

---

modules/jwt/src/main/scala/io/renku/search/jwt/JwtBorer.scala
modules/jwt/src/main/scala/io/renku/search/jwt/RenkuToken.scala
modules/jwt/src/test/resources/jwt1.json
modules/jwt/src/test/resources/jwt2.json
modules/jwt/src/test/scala/io/renku/search/jwt/JwtBorerSpec.scala
modules/jwt/src/test/scala/io/renku/search/jwt/RenkuTokenSpec.scala
modules/openid-keycloak/src/main/scala/io/renku/openid/keycloak/DefaultJwtVerify.scala
modules/openid-keycloak/src/main/scala/io/renku/openid/keycloak/Jwks.scala
modules/openid-keycloak/src/main/scala/io/renku/openid/keycloak/JwtError.scala
modules/openid-keycloak/src/main/scala/io/renku/openid/keycloak/JwtVerify.scala
modules/search-api/src/main/scala/io/renku/search/api/Routes.scala
modules/search-api/src/main/scala/io/renku/search/api/auth/Authenticate.scala
modules/search-api/src/main/scala/io/renku/search/api/auth/ClaimToContext.scala
modules/search-api/src/main/scala/io/renku/search/api/data/AuthContext.scala
modules/search-api/src/main/scala/io/renku/search/api/routes/SearchRoutes.scala
modules/search-api/src/main/scala/io/renku/search/api/tapir/Params.scala
modules/search-api/src/test/scala/io/renku/search/api/auth/AuthenticateSpec.scala
modules/search-api/src/test/scala/io/renku/search/api/auth/ClaimToContextSpec.scala
modules/search-solr-client/src/main/scala/io/renku/search/solr/SearchRole.scala
modules/search-solr-client/src/main/scala/io/renku/search/solr/documents/EntityMembers.scala
modules/search-solr-client/src/main/scala/io/renku/search/solr/query/LuceneQueryEncoders.scala
modules/search-solr-client/src/main/scala/io/renku/search/solr/query/LuceneQueryInterpreter.scala
modules/search-solr-client/src/test/scala/io/renku/search/solr/client/SearchSolrClientSpec.scala
modules/search-solr-client/src/test/scala/io/renku/search/solr/query/LuceneQueryEncoderSpec.scala
modules/search-solr-client/src/test/scala/io/renku/search/solr/query/LuceneQueryInterpreterSpec.scala

- Reads the `Authorization Bearer` token from the request (if present) and decodes it to a pre-known structure `RenkuToken`
- a caller is an admin, if the role `renku-admin` is in `realmAccess.roles`
- add another `AuthContext` for admins and convert to existing `SearchRole.Admin` which will remove any constraints to a given user query
- Refactors auth-code in search routes for better testability

Enable admins to query without restrictions

---

modules/solr-client/src/main/scala/io/renku/solr/client/QueryData.scala
modules/solr-client/src/main/scala/io/renku/solr/client/ResponseBody.scala
modules/solr-client/src/main/scala/io/renku/solr/client/SolrSort.scala
modules/solr-client/src/main/scala/io/renku/solr/client/SubQuery.scala
modules/solr-client/src/test/scala/io/renku/solr/client/SolrClientSpec.scala

In order to return results from related documents, this adds support for using the [sub-query document transformer](https://solr.apache.org/guide/solr/latest/query-guide/document-transformers.html#subquery) to the solr-client library. 
Solr allows to run sub queries per document using a document
transformer. For this, a synthetic field needs to be added to the
field list of the main query and a `:[subquery]` appended to it, e.g.
`creator:[subquery]`. Then the actual sub query can be added to the
`params` section of the main query - prefixed by the field name. The
sub query works exactly like a main query, the parameters need only to
be prefixed so solr can do the query and associate the result
correctly. Solr will execute that query and adds the results as a
value to the defined field. …

Extend solr client to support subqueries

---

flake.nix
modules/config-values/src/main/scala/io/renku/search/config/ConfigValues.scala
modules/openid-keycloak/src/main/scala/io/renku/openid/keycloak/JwtVerifyConfig.scala
modules/openid-keycloak/src/test/scala/io/renku/openid/keycloak/DefaultJwtVerifySpec.scala

The url patterns for expected issuers must be set to be able to start the search api service. It can be set using environment variable `RS_JWT_ALLOWED_ISSUER_URL_PATTERNS`.

Make jwt issuer url setting required

---

modules/search-api/src/main/scala/io/renku/search/api/Routes.scala

This little change is meant as preparation to mount the search endpoint in a more flexible way and to finally allow to provide a `/version` endpoint for the (entire) search service.
The idea is that we remove the `stripPrefix` in gateway and pass the request as-is to the search service. The current public path should not change, therefore it stays as `/api/search` and the current "search" endpoint will be `/api/search/query`. Later a version `/api/search/version` and potentially other public endpoints can be provided easily without changing gateway. Currently it is not possible to provide more endpoints without editing the gateway configuration (besides putting everything under `/search` which is too strange).
This commit allows clients (UI) to use the new path for doing search queries, …

Additionally mount search endpoint to /api/search/query

---

project/DockerImagePlugin.scala

The current `eclipse-temurin:21-jre` image has now a user already present with `uid=1000`. So creating `searchuser` fails when building the image. The comment above indicates, that it is necessary to have a user with this specific `uid=1000`. So this change switches to the pre-installed `ubuntu` user to fix this.

Set docker daemon user to 'ubuntu'

---

modules/commons/src/main/scala/io/renku/search/common/UrlPattern.scala
modules/commons/src/test/scala/io/renku/search/common/UrlPatternSpec.scala

Patterns `*` and `**` are semantically equal. The latter version was not rendered correctly. Reading these two would result into the same pattern value.

Fix rendering and reading different match-all patterns

---

modules/json/src/main/scala/io/renku/json/EncoderSupport.scala
modules/search-solr-client/src/main/scala/io/renku/search/solr/schema/EntityDocumentSchema.scala
modules/search-solr-client/src/main/scala/io/renku/search/solr/schema/Migrations.scala
modules/search-solr-client/src/test/scala/io/renku/search/solr/client/SearchSolrClientSpec.scala
modules/solr-client/src/main/scala/io/renku/solr/client/schema/Analyzer.scala
modules/solr-client/src/main/scala/io/renku/solr/client/schema/FieldType.scala
modules/solr-client/src/main/scala/io/renku/solr/client/schema/Filter.scala
modules/solr-client/src/main/scala/io/renku/solr/client/schema/SchemaCommand.scala
modules/solr-client/src/main/scala/io/renku/solr/client/schema/SchemaJsonCodec.scala
modules/solr-client/src/test/scala/io/renku/solr/client/SearchCaseInsensitiveSpec.scala
modules/solr-client/src/test/scala/io/renku/solr/client/SolrClientSpec.scala
modules/solr-client/src/test/scala/io/renku/solr/client/migration/SolrMigratorSpec.scala
modules/solr-client/src/test/scala/io/renku/solr/client/schema/BorerJsonCodecTest.scala

This filter adds prefixes of words into the index, so an normal query finds documents on prefixes starting with 2 letters and up to 8.
Refs: #168

Configure text fields with 'edgeNGram' filter enabling prefix search

---

modules/redis-client/src/main/scala/io/renku/redis/client/RedisQueueClient.scala

It sometimes occurs that the redis connection is to a read-only replica. In this case, setting the last seen message id fails and the process restarts. To avoid restarts, just log a warning, because processing duplicates is not problematic.

Don't fail when the last message id cannot be set

---

flake.nix
modules/commons/src/main/scala/io/renku/search/model/Visibility.scala

The API docs should show lower case visibility values, as they are returned from the server.
Closes: #160

Fix casing in api docs for visibility values

---

flake.nix
modules/config-values/src/main/scala/io/renku/search/config/QueuesConfig.scala
modules/search-cli/src/main/scala/io/renku/search/cli/groups/AddCmd.scala
modules/search-cli/src/main/scala/io/renku/search/cli/groups/MemberAddCmd.scala
modules/search-cli/src/main/scala/io/renku/search/cli/groups/MemberRemoveCmd.scala
modules/search-cli/src/main/scala/io/renku/search/cli/groups/MemberUpdateCmd.scala
modules/search-cli/src/main/scala/io/renku/search/cli/groups/RemoveCmd.scala
modules/search-cli/src/main/scala/io/renku/search/cli/groups/UpdateCmd.scala
modules/search-cli/src/main/scala/io/renku/search/cli/projects/CreateCmd.scala
modules/search-cli/src/main/scala/io/renku/search/cli/projects/MemberAddCmd.scala
modules/search-cli/src/main/scala/io/renku/search/cli/projects/MemberRemoveCmd.scala
modules/search-cli/src/main/scala/io/renku/search/cli/projects/MemberUpdateCmd.scala
modules/search-cli/src/main/scala/io/renku/search/cli/projects/RemoveCmd.scala
modules/search-cli/src/main/scala/io/renku/search/cli/projects/UpdateCmd.scala
modules/search-cli/src/main/scala/io/renku/search/cli/users/AddCmd.scala
modules/search-cli/src/main/scala/io/renku/search/cli/users/RemoveCmd.scala
modules/search-cli/src/main/scala/io/renku/search/cli/users/UpdateCmd.scala
modules/search-provision/src/main/scala/io/renku/search/provision/MessageHandlers.scala
modules/search-provision/src/test/scala/io/renku/search/provision/ProvisioningSuite.scala

The stream is not only for search, rename it according to the producer. See comments in https://github.com/SwissDataScienceCenter/renku-data-services/pull/377/files/acba8f289afa1023a54c40d6836139e44a964c98#r1743224983

Rename stream to `data_service.all_events`

---

modules/events/src/main/scala/io/renku/search/events/MessageId.scala
modules/redis-client/src/main/scala/io/renku/redis/client/RedisQueueClient.scala
modules/redis-client/src/test/scala/io/renku/redis/client/RedisQueueClientSpec.scala
modules/renku-redis-client/src/main/scala/io/renku/queue/client/QueueClient.scala
modules/renku-redis-client/src/main/scala/io/renku/queue/client/QueueClientImpl.scala
modules/search-provision/src/main/scala/io/renku/search/provision/BackgroundProcessManage.scala
modules/search-provision/src/main/scala/io/renku/search/provision/MessageHandlers.scala
modules/search-provision/src/main/scala/io/renku/search/provision/Microservice.scala
modules/search-provision/src/main/scala/io/renku/search/provision/Routes.scala
modules/search-provision/src/main/scala/io/renku/search/provision/Services.scala
modules/search-provision/src/main/scala/io/renku/search/provision/reindex/ReIndexDocument.scala
modules/search-provision/src/main/scala/io/renku/search/provision/reindex/ReIndexService.scala
modules/search-provision/src/test/scala/io/renku/search/provision/BackgroundProcessManageSpec.scala
modules/search-provision/src/test/scala/io/renku/search/provision/ProvisioningSuite.scala
modules/search-provision/src/test/scala/io/renku/search/provision/TestServices.scala
modules/search-provision/src/test/scala/io/renku/search/provision/reindex/ReIndexServiceSpec.scala
modules/search-solr-client/src/main/scala/io/renku/search/solr/client/SearchSolrClient.scala
modules/search-solr-client/src/main/scala/io/renku/search/solr/client/SearchSolrClientImpl.scala
modules/search-solr-client/src/main/scala/io/renku/search/solr/query/SolrToken.scala
modules/search-solr-client/src/test/scala/io/renku/search/solr/client/SearchSolrClientSpec.scala
nix/dev-scripts.nix
nix/scripts/redis-list-streams
nix/scripts/redis-stream-info

Exposes an endpoint on the search-provision service to drop the current index and re-read everything from the redis stream. This allows to re-create the entire index from the raw data.

Allow to re-create the index from the redis stream

---

modules/search-provision/src/main/scala/io/renku/search/provision/Microservice.scala
modules/search-provision/src/main/scala/io/renku/search/provision/reindex/ReIndexService.scala
modules/solr-client/src/main/scala/io/renku/solr/client/migration/MigrateResult.scala
modules/solr-client/src/main/scala/io/renku/solr/client/migration/SchemaMigrator.scala
modules/solr-client/src/test/scala/io/renku/solr/client/migration/SolrMigratorSpec.scala

Migrations can communicate whether a re-index is necessary. When the schema migrations run and there is at least one migration requiring a re-index, the solr index will be rebuild on startup.
Closes: #184

Allow to run re-indexing as result of a schema migration

---

modules/search-provision/src/main/scala/io/renku/search/provision/Microservice.scala
modules/solr-client/src/main/scala/io/renku/solr/client/migration/MigrateResult.scala
modules/solr-client/src/main/scala/io/renku/solr/client/migration/SchemaMigration.scala
modules/solr-client/src/main/scala/io/renku/solr/client/migration/SchemaMigrator.scala
modules/solr-client/src/test/scala/io/renku/solr/client/migration/SolrMigratorSpec.scala

The solr schema can be fetched and it is used to test each command in the schema migration if it had already been applied. If not, the command is run and otherwise it is ignored.
With this change it is possible to drop solr entirely, including schema information. On restart, the schema will be fixed by running those changes that haven't been applied.

Run schema migration commands only if not already applied

---

.github/workflows/ci.yml
project/ReadmePlugin.scala

If the ci runs on a push to the main branch, the readme checks should be skipped.

Fix github action

---

modules/solr-client/src/main/scala/io/renku/solr/client/SolrClientImpl.scala

This bug results in schema migrations not being run on startup and thus a not functioning service.

Attach credentials to solr schema requests

---

modules/http4s-commons/src/main/scala/io/renku/search/http/HttpServer.scala
modules/search-api/src/main/scala/io/renku/search/api/SearchServer.scala

- Requests and responses are now logged at debug level and thus hidden by default
- Add `Renku-Auth-Id-Token` to the list of sensitive headers so they don't appear in logs (the header is not used, but being added to the requests)

Log requests and response at debug level

---

modules/search-solr-client/src/main/scala/io/renku/search/solr/client/RenkuEntityQuery.scala
modules/search-solr-client/src/main/scala/io/renku/search/solr/client/SearchSolrClientImpl.scala
modules/search-solr-client/src/main/scala/io/renku/search/solr/query/LuceneQueryInterpreter.scala
modules/search-solr-client/src/main/scala/io/renku/search/solr/query/SolrQuery.scala
modules/search-solr-client/src/main/scala/io/renku/search/solr/query/SolrToken.scala
modules/search-solr-client/src/test/scala/io/renku/search/solr/client/RenkuEntityQuerySpec.scala
modules/search-solr-client/src/test/scala/io/renku/search/solr/query/LuceneQueryInterpreterSpec.scala
modules/solr-client/src/main/scala/io/renku/solr/client/QueryData.scala
modules/solr-client/src/main/scala/io/renku/solr/client/SolrClientImpl.scala

- Move additional query constraints into single place (SearchSolrClient)
- Have a separate class for converting a user query into the final solr query (to be easier to test and have a dedicated place for this important piece)
- Add more tests for query amendments

Refactor querying for renku enitities

---

modules/solr-client/src/main/scala/io/renku/solr/client/CursorMark.scala
modules/solr-client/src/main/scala/io/renku/solr/client/QueryData.scala
modules/solr-client/src/main/scala/io/renku/solr/client/SolrSort.scala
modules/solr-client/src/main/scala/io/renku/solr/client/schema/FieldName.scala
modules/solr-client/src/test/scala/io/renku/solr/client/SolrClientSpec.scala

This adds the ability to use a cursor for paginated results to the solr client library.

Add pagination with cursor to solr client

---

.github/workflows/auto-approve.yml

The PRs for dependency updates should get merged automatically. Now it requires a approval for merging which this workflow should do.

Auto-approve dependency updates from RenkuBot
